### ISSUE TITLE
Opportunities Page doesn't populate Available Until field properly

### ISSUE THREAD

**Issue by keshashah** [systers/crowdmap#23]
Steps to Reproduce:
1. Login to pc-crowdmap-dev.systers.org/login
2. Click on Submit An Opportunity
3. Fill in details and click on Submit. 
4. You will redirected to a success page, which has link to "Return to Opportunities". Click that link.
5. In the list of available resources, the newly added resource has "Available until" field overridden by "0000-00-00 00:00:00", where as it should be the datetime entered while filling the details for that resource.

Demo: http://screencast.com/t/OYmlaZd1x

**Comment by jproft** [comment]
@keshashah Apologies for not noticing this issue until now! The problem was that the date format given by the date picker (mm/dd/yyyy) was not compatible with the MySQL datetime (0000-00-00 00:00:00) database structure. After changing the structure in the database (I switched it to varchar), the available from and available until fields started working. :)

**Comment by keshashah** [comment]
No worries. Thanks for fixing it @jproft :)
