### ISSUE TITLE
Contact Us- Message not being sent

### ISSUE THREAD

**Issue by keshashah** [systers/crowdmap#24]
In this issue, when you try to send a message via Contact Us tab - inspite of all details being correct - one lands up with an error saying - "There was an error sending your message."

Screencast: http://screencast.com/t/YMp8RuBrlY

Steps to Reproduce:
1. Go to Contact Us Tab
2. Fill in details
3. Click on Send Message

**Comment by rosariorobinson** [comment]
When I click on the link, nothing happens. I tried Chrome and Firefox.

**Comment by keshashah** [comment]
![image](https://cloud.githubusercontent.com/assets/2563540/8551775/2fcff4f0-24f6-11e5-8b4e-4aa418fbb885.png)

This is a screenshot. Maybe it helps!

**Comment by keshashah** [comment]
Same as before - I am attaching screenshot for reference. Let me know if you have questions.

![image](https://cloud.githubusercontent.com/assets/2563540/8551868/e9ba1b70-24f6-11e5-9cab-ecda43ba4a26.png)

**Comment by rosariorobinson** [comment]
@divyaupadhyay can you look at this please?  As well as #25. Is the latest code on GitHub? Is the latest code from successful build on the server? 

@keshashah are you accessing this from our server.

@jproft @jenpaff make sure we have the latest code on GitHub so that Kesha is running from the latest. 

Maybe we need to define a schedule of when we migrate latest build to Systers crowdmap server.

**Comment by jproft** [comment]
I think the problem is that the site email address isn't valid rather than a problem in the code. From what I can remember, neither Jen nor I changed anything with the contact page. Will look into it ASAP.

**Comment by jenpaff** [comment]
Yes, Julia is right, we never changed anything with the contact page. Could you try a different E-Mail address? Feel free to use mine jenpaff0@gmail.com

**Comment by divyaupadhyay** [comment]
I also received the same errors as @keshashah testing this issue and #25 . Looking into it.

**Comment by keshashah** [comment]
@jenpaff With your email address too, I get the same error. PFA screenshot.

![image](https://cloud.githubusercontent.com/assets/2563540/8601602/a3b69d70-268a-11e5-9439-51ef0591d8fa.png)

**Comment by jproft** [comment]
@keshashah By "site email address" I meant the one that the contact messages are sent to rather than the address inputted into the contact form. I had a few minutes to look into it yesterday and I changed that address then, but it didn't seem to have an immediate effect. I'm going to look in the database to see what the email address is and will report back. :)

**Comment by jproft** [comment]
Update: The problem is that the mail settings on the server have not been configured. It's not an issue with Ushahidi. :) Just so everyone knows, the exact error being thrown is

exception 'Swift_ConnectionException' with message 'Sending failed using mail() as PHP's default mail() function returned boolean FALSE.'

which indicates that the server is currently unable to send emails with PHP. I will look into getting this fixed, but at least we now know that it's not a problem with the codebase!

**Comment by keshashah** [comment]
That sounds good!

**Comment by jproft** [comment]
@keshashah Installing sendmail on the server and changing the Ushahidi mail configuration did the trick. Emails are now being sent. :)

**Comment by keshashah** [comment]
:+1:  @jproft :100:
